# Generated by Django 6.0.5 on 2026-05-29 06:18

import datetime
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField()),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 1), ('sensor_chart', 6), ('coordinates', 8), ('code', 11), ('document', 12), ('pull_quote', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'KTM-001'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'temperature_c | humidity_rh | pressure_hpa | pm2_5 | co2_ppm'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '24', 'help_text': 'Hours of history to show'}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('station_id', 2), ('sensor', 3), ('hours', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('label', 5), ('latitude', 7), ('longitude', 7), ('altitude_m', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'python'}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('language', 9), ('code', 10), ('caption', 5)]], {}), 12: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})})),
                ('registration_info', wagtail.fields.RichTextField(blank=True, help_text='Company registration details, MOA excerpt.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField()),
                ('email_research', models.EmailField(default='info@himalayansciences.org', max_length=254)),
                ('email_education', models.EmailField(blank=True, max_length=254)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DataPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('api_docs', wagtail.fields.RichTextField(blank=True, help_text='API documentation text.')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tagline', models.CharField(default='Science rooted in place. Data open to all.', max_length=200)),
                ('mission', models.TextField(help_text='One clear statement of what HICS does and why.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional 2–3 sentence expansion below mission.')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InstrumentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InstrumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('status', models.CharField(choices=[('active', 'Active — collecting data'), ('building', 'Under construction'), ('planned', 'Planned'), ('retired', 'Retired')], default='planned', max_length=20)),
                ('summary', models.TextField(help_text='One sentence shown on index cards.', max_length=300)),
                ('what_it_measures', wagtail.fields.RichTextField(help_text='Plain explanation of what this instrument does.')),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 1), ('sensor_chart', 6), ('coordinates', 8), ('code', 11), ('document', 12), ('pull_quote', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'KTM-001'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'temperature_c | humidity_rh | pressure_hpa | pm2_5 | co2_ppm'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '24', 'help_text': 'Hours of history to show'}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('station_id', 2), ('sensor', 3), ('hours', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('label', 5), ('latitude', 7), ('longitude', 7), ('altitude_m', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'python'}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('language', 9), ('code', 10), ('caption', 5)]], {}), 12: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})})),
                ('github_url', models.URLField(blank=True)),
                ('station_id', models.CharField(blank=True, help_text='If deployed: station ID (e.g. KTM-001)', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LabNoteIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LabNotePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('experiment', 'Experiment'), ('build', 'Build Log'), ('field', 'Field Dispatch'), ('analysis', 'Analysis')], default='observation', max_length=20)),
                ('date', models.DateField(default=datetime.date.today)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(help_text='2–3 sentences shown on index page.', max_length=400)),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 1), ('sensor_chart', 6), ('coordinates', 8), ('code', 11), ('document', 12), ('pull_quote', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'KTM-001'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'temperature_c | humidity_rh | pressure_hpa | pm2_5 | co2_ppm'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '24', 'help_text': 'Hours of history to show'}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('station_id', 2), ('sensor', 3), ('hours', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('label', 5), ('latitude', 7), ('longitude', 7), ('altitude_m', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'python'}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('language', 9), ('code', 10), ('caption', 5)]], {}), 12: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})})),
            ],
            options={
                'ordering': ['-date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResearchIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LabNoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_note', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='pages.labnotepage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_note_tags', to='taggit.tag')),
            ],
            options={
                'unique_together': {('lab_note', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='labnotepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='pages.LabNoteTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('journal', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('doi', models.CharField(blank=True, max_length=200)),
                ('abstract', models.TextField(blank=True)),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProgrammePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('programme_type', models.CharField(choices=[('cosmic-ray', 'Cosmic Ray / Muon Physics'), ('meteor', 'Meteor Astronomy'), ('atmospheric', 'Atmospheric Science'), ('seismology', 'Seismology'), ('building-physics', 'Building Physics'), ('traditional-knowledge', 'Traditional Ecological Knowledge')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('paused', 'Paused')], default='planned', max_length=20)),
                ('summary', models.TextField(help_text='One paragraph, shown on index page.', max_length=300)),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 1), ('sensor_chart', 6), ('coordinates', 8), ('code', 11), ('document', 12), ('pull_quote', 10)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'default': 'KTM-001'}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'temperature_c | humidity_rh | pressure_hpa | pm2_5 | co2_ppm'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '24', 'help_text': 'Hours of history to show'}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('station_id', 2), ('sensor', 3), ('hours', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('label', 5), ('latitude', 7), ('longitude', 7), ('altitude_m', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'python'}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.StructBlock', [[('language', 9), ('code', 10), ('caption', 5)]], {}), 12: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})})),
                ('publications', models.ManyToManyField(blank=True, to='pages.publication')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
