# Generated by Django 5.1.15 on 2026-05-31 13:49

import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EducationProgrammePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('programme_type', models.CharField(choices=[('residency', 'School Science Residency'), ('fellowship', 'Youth Research Fellowship'), ('camp', 'Annual Science Camp'), ('teachers', 'Teacher Professional Development'), ('computing', 'Scientific Computing Courses'), ('public', 'Public Science Programme')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('accepting', 'Accepting Applications')], default='planned', max_length=20)),
                ('summary', models.TextField(help_text='Short description shown on index page.', max_length=400)),
                ('body', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'superscript'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('sensor_chart', wagtail.blocks.StructBlock([('station_id', wagtail.blocks.CharBlock(default='KTM-001')), ('sensor', wagtail.blocks.CharBlock(help_text='temperature_c | humidity_rh | pressure_hpa | pm2_5 | co2_ppm')), ('hours', wagtail.blocks.CharBlock(default='24', help_text='Hours of history to show')), ('caption', wagtail.blocks.CharBlock(required=False))])), ('coordinates', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.CharBlock()), ('longitude', wagtail.blocks.CharBlock()), ('altitude_m', wagtail.blocks.CharBlock(required=False))])), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(default='python')), ('code', wagtail.blocks.TextBlock()), ('caption', wagtail.blocks.CharBlock(required=False))])), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('pull_quote', wagtail.blocks.TextBlock())], blank=True)),
                ('target_audience', models.CharField(blank=True, help_text="e.g. 'High school students, Grades 9-11'", max_length=200)),
                ('contact_email', models.EmailField(default='info@himalayansciences.org', max_length=254)),
                ('contact_subject', models.CharField(blank=True, help_text='Pre-filled email subject line.', max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LearnIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OpenKnowledgePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'blockquote', 'superscript'])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('sensor_chart', wagtail.blocks.StructBlock([('station_id', wagtail.blocks.CharBlock(default='KTM-001')), ('sensor', wagtail.blocks.CharBlock(help_text='temperature_c | humidity_rh | pressure_hpa | pm2_5 | co2_ppm')), ('hours', wagtail.blocks.CharBlock(default='24', help_text='Hours of history to show')), ('caption', wagtail.blocks.CharBlock(required=False))])), ('coordinates', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(required=False)), ('latitude', wagtail.blocks.CharBlock()), ('longitude', wagtail.blocks.CharBlock()), ('altitude_m', wagtail.blocks.CharBlock(required=False))])), ('code', wagtail.blocks.StructBlock([('language', wagtail.blocks.CharBlock(default='python')), ('code', wagtail.blocks.TextBlock()), ('caption', wagtail.blocks.CharBlock(required=False))])), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('pull_quote', wagtail.blocks.TextBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
