# Generated by Django 5.1.15 on 2026-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_educationindexpage_educationprogrammepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprogrammepage',
            name='programme_type',
            field=models.CharField(choices=[('cosmic-ray', 'Cosmic Ray / Muon Physics'), ('meteor', 'Meteor Astronomy'), ('atmospheric', 'Atmospheric Science'), ('seismology', 'Seismology'), ('building-physics', 'Building Physics'), ('traditional-knowledge', 'Traditional Ecological Knowledge'), ('glaciology', 'Glaciology and Cryosphere'), ('computational', 'Computational Science')], max_length=30),
        ),
    ]
