# Generated by Django 5.1.15 on 2026-05-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_aboutpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_title',
            field=models.CharField(blank=True, default='Send a direct message', max_length=200),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='success_message',
            field=models.TextField(blank=True, default='Thank you! Your message has been sent successfully. We will get back to you shortly.'),
        ),
    ]
