# Generated by Django 5.1.15 on 2026-05-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude_m', models.FloatField()),
                ('location_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('planned', 'Planned')], default='planned', max_length=20)),
                ('api_key_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['station_id'],
            },
        ),
        migrations.CreateModel(
            name='MeteorDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('image', models.ImageField(upload_to='meteors/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='meteors/thumbs/%Y/%m/')),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('shower_association', models.CharField(blank=True, max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meteor_detections', to='instruments.station')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_rh', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('pm1_0', models.FloatField(blank=True, null=True)),
                ('pm2_5', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('co2_ppm', models.FloatField(blank=True, null=True)),
                ('co_ppm', models.FloatField(blank=True, null=True)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='instruments.station')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='instruments_station_9c4467_idx')],
            },
        ),
    ]
